server:
  port: 9595

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tour?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: tmstarry@163.com
    password: tmstarry163
  servlet:
    multipart:
      max-file-size: 50MB

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: info
    top.tmstarry.tour: debug

